config/routes.rb
Rails.application.routes.draw do
  resources :sections
  #resources :courses

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    unlocks: 'users/unlocks'
  }

  authenticated :user do
    root 'courses#index', as: :authenticated_root
  end

  devise_scope :user do
    unauthenticated :user do
      root to: 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  # authenticated :user do
  #   root 'placeholder#welcome', as: :authenticated_root
  # end

  devise_scope :user do
    root to: "devise/sessions#new"
  end

  # lab3 part
  # get 'student_information', to: 'students#information', as: 'student_information'

  # lab3 part
  # resources :students do
  #   collection do
  #     # post 'setgpa' 
  #     post 'settime'
  #  end
  # end 


  # # Defines the root path route ("/")
  # root "courses#index"


  resources :courses, only: [:index]
  
   # Reset database route
  post '/reset_courses', to: 'courses#reset'

  # Edit course route
  get 'courses/edit', to: 'courses#edit'

  # New course route
  get 'courses/new', to: 'courses#new'

  #Redirect show page to course index
  get 'courses/:id', to: 'courses#index'

  get 'courses/:id/sections/:id', to: 'courses#index'

  # courses/course_id/section/:id route
  resources :courses do
    resources :sections
  end


  # config/routes.rb
  resources :role_requests do
    member do
      put 'approve'
      put 'deny'
    end
  end

end

app/models/section.rb
class Section < ApplicationRecord
    self.table_name = "sections"
    belongs_to :instructor, foreign_key: 'faculty_email', class_name: 'Instructor'
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
    before_action :set_course, only: [:new, :create] 
    before_action :set_section, only: [:show, :edit, :update, :destroy]
  
    # GET /courses/:course_id/sections/new
    def new
      @section = @course.sections.new
    end
  
    # POST /courses/:course_id/sections for adding a new section
    def create
      @section = @course.sections.new(section_params)
  
      if @section.save
        redirect_to course_path(@course), notice: 'Section was successfully created.'
      else
        render :new
      end
    end
  
    # GET /sections/:id/edit 
    def edit
      @course = Course.find(params[:course_id])
      @section = Section.find(params[:id])
    end
    
    def show
      @course = Course.find(params[:course_id])
      @section = Section.find(params[:id])
    end

    # PATCH/PUT /sections/:id for editing a section
    def update
      @course = Course.find(params[:course_id])
      if @section.update(section_params)
        redirect_to course_section_path(@course, @section), notice: 'Section was successfully updated.'
      else
        render :edit, notice: 'Section was NOT successfully updated.'
      end
    end
  
    # DELETE /sections/:id
    def destroy
        @section = Section.find(params[:id])
        @section.destroy
        redirect_to authenticated_root_path, notice: 'Section was successfully destroyed.'
    end
  
    private

      def set_course
        @course = Course.find(params[:course_id])
      end
  

      def set_section
        @section = Section.find(params[:id])
      end

      def section_params
        params.require(:section).permit(:section_id, :start_time, :end_time, :weekday, :has_grader, :start_date, :end_date, :semester_code, :campus, :faculty_email, :course_id)
      end
      
      
  end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/views/sections/_form.html.erb
<%= form_with(model: section) do |form| %>
  <% if section.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(section.errors.count, "error") %> prohibited this section from being saved:</h2>

      <ul>
        <% section.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/sections/_section.html.erb
<div id="<%= dom_id section %>">
</div>

app/views/sections/edit.html.erb
  <%= form_with(model: [@course, @section], local: true) do |form| %>
  
  <div class="form-box">
    <h3 style="margin-bottom:20px;">Edit Section <%=@section.section_id%></h3>
    <div class="field">
       <%= form.label :section_id %><br>
  <%= form.number_field :section_id, required: true %>
  </div>

  <div class="field">
    <%= form.label :start_time %><br>
    <%= form.text_field :start_time, required: true %>
  </div>

  <div class="field">
    <%= form.label :end_time %><br>
    <%= form.text_field :end_time, required: true %>
  </div>

  <div class="field">
    <%= form.label :weekday %><br>
    <%= form.text_field :weekday, required: true %>
  </div>

  <div class="field">
    <%= form.label :has_grader %><br>
    <%= form.check_box :has_grader, required: false %>
  </div>

  <div class="field">
    <%= form.label :start_date %><br>
    <%= form.date_field :start_date, required: true %>
  </div>

  <div class="field">
    <%= form.label :end_date %><br>
    <%= form.date_field :end_date, required: true %>
  </div>

  <div class="field">
    <%= form.label :semester_code %><br>
    <%= form.text_field :semester_code, required: true %>
  </div>

  <div class="field">
    <%= form.label :campus %><br>
    <%= form.text_field :campus, required: true %>
  </div>

  <div class="field">
    <%= form.label :faculty_email, "Instructor Email" %><br>
    <%= form.collection_select(:faculty_email, Instructor.all, :faculty_email, :full_name, { prompt: true }, required: true) %>
  </div>

  <div class="field">
    <%= form.label :course_id %><br>
    <%= form.number_field :course_id, value: @course.course_id, readonly: true %>
  </div>

    <div class="actions" style="float:left;">
    <%= form.submit "Save Section" %>
  </div>


    <% end %>

    <br><br>
    
    <div>
      <%= link_to "Back to courses", courses_path %>
    </div>

app/views/sections/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Sections</h1>

<div id="sections">
  <% @sections.each do |section| %>
    <%= render section %>
    <p>
      <%= link_to "Show this section", section %>
    </p>
  <% end %>
</div>

<%= link_to "New section", new_section_path %>

app/views/sections/new.html.erb

  <%= form_with(model: [@course, @section], local: true) do |form| %>
  
  <div class="form-box">
    <h3 style="margin-bottom:20px;">Add Section for Course <%=@section.course_id%></h3>
    <div class="field">
       <%= form.label :section_id %><br>
  <%= form.number_field :section_id, required: true %>
  </div>

  <div class="field">
    <%= form.label :start_time %><br>
    <%= form.time_field :start_time, required: true %>
  </div>

  <div class="field">
    <%= form.label :end_time %><br>
    <%= form.time_field :end_time, required: true %>
  </div>

  <div class="field">
    <%= form.label :weekday %><br>
    <%= form.text_field :weekday, required: true %>
  </div>

  <div class="field">
    <%= form.label :has_grader %><br>
    <%= form.check_box :has_grader, required: false %>
  </div>

  <div class="field">
    <%= form.label :start_date %><br>
    <%= form.date_field :start_date, required: true %>
  </div>

  <div class="field">
    <%= form.label :end_date %><br>
    <%= form.date_field :end_date, required: true %>
  </div>

  <div class="field">
    <%= form.label :semester_code %><br>
    <%= form.text_field :semester_code, required: true %>
  </div>

  <div class="field">
    <%= form.label :campus %><br>
    <%= form.text_field :campus, required: true %>
  </div>

  <div class="field">
    <%= form.label :faculty_email, "Instructor Email" %><br>
    <%= form.collection_select(:faculty_email, Instructor.all, :faculty_email, :full_name, { prompt: true }, required: true) %>
  </div>

  <div class="field">
    <%= form.label :course_id %><br>
    <%= form.number_field :course_id, value: @course.course_id, readonly: true %>
  </div>

    <div class="actions" style="float:left;">
    <%= form.submit "Add Section" %>
  </div>

    <% end %>

    <br><br>
    
    <div>
      <%= link_to "Back to courses", courses_path %>
    </div>

app/views/sections/show.html.erb
<%
=begin%>
 Show if operation is successful 
<%
=end%>
<p style="color: green"><%= notice %></p>

<%= render @section %>

<div>
  <%= link_to "Edit this section", edit_course_section_path(@course, @section) %> |
  <%= link_to "Back to courses", courses_path %>

  <%#= button_to "Destroy this section", @section, method: :delete %>
</div>