config/routes.rb
Rails.application.routes.draw do
  resources :sections
  #resources :courses

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    unlocks: 'users/unlocks'
  }

  authenticated :user do
    root 'courses#index', as: :authenticated_root
  end

  devise_scope :user do
    unauthenticated :user do
      root to: 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  # authenticated :user do
  #   root 'placeholder#welcome', as: :authenticated_root
  # end

  devise_scope :user do
    root to: "devise/sessions#new"
  end

  # lab3 part
  # get 'student_information', to: 'students#information', as: 'student_information'

  # lab3 part
  # resources :students do
  #   collection do
  #     # post 'setgpa' 
  #     post 'settime'
  #  end
  # end 


  # # Defines the root path route ("/")
  # root "courses#index"


  resources :courses, only: [:index]
  
   # Reset database route
  post '/reset_courses', to: 'courses#reset'

  # Edit course route
  get 'courses/edit', to: 'courses#edit'

  # New course route
  get 'courses/new', to: 'courses#new'

  #Redirect show page to course index
  get 'courses/:id', to: 'courses#index'

  get 'courses/:id/sections/:id', to: 'courses#index'

  # courses/course_id/section/:id route
  resources :courses do
    resources :sections
  end


  # config/routes.rb
  resources :role_requests do
    member do
      put 'approve'
      put 'deny'
    end
  end

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: %i[ show edit update destroy ]

  # GET /courses or /courses.json
  def index
    if user_signed_in?
      @user = current_user 
      @person = Person.find(@user.email)
    end
    # only the course same as selected params
    @pagy, @courses = pagy(Course.all)
    @academic_careers = Course.pluck(:academic_career).uniq.compact
    @campus = Course.pluck(:campus).uniq.compact
    @term = Course.pluck(:term).uniq.compact
    
    #Up to 500 items will show when searching
    if params[:academic_career].present?
      @pagy, @courses = pagy(@courses.where(academic_career: params[:academic_career]), items:500)
    end
    
    if params[:campus].present?
      @pagy, @courses = pagy(@courses.where(campus: params[:campus]), items:500)
    end
    
    if params[:term].present?
      @pagy, @courses = pagy(@courses.where(term: params[:term]), items:500)
    end
    
    if params[:search_query].present?
      @pagy, @courses = pagy(@courses.where("catalog_number LIKE ?","%#{params[:search_query]}%"), items:500)
    end 
  end

  # GET /courses/1 or /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
    @course = Course.find(params[:id])
  end

  # POST /courses or /courses.json for adding a new course
  def create
    @course = Course.new(course_params)

    if @course.save
      redirect_to @course, notice: 'Course was successfully created.'
    else
      render 'new', notice: 'Course was NOT successfully created.'
    end
  end

  # PATCH/PUT /courses/1 or /courses/1.json for editing a course
  def update
    @course = Course.find(params[:id])
    if @course.update(course_params)
      # successful update
      redirect_to @course, notice: 'Course was successfully updated.'
    else
      # update errors
      render :edit, notice: 'Course was NOT successfully updated.'
    end
  end
  

  # DELETE /courses/1 or /courses/1.json
  def destroy
    @course = Course.find(params[:id])
    @course.destroy
    redirect_to courses_url, notice: 'Course was successfully deleted.'
  end

  # reset database
  def reset
    if params[:reset] == 'true'
      # Call to reset the database
      load "#{Rails.root}/db/seeds.rb"
      
      # Redirect to the index page to generate a clean URL without parameters
      redirect_to courses_path, notice: "Database reset successful."
    else
      redirect_to courses_path, notice: "Database reset failed"
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def course_params
      params.require(:course).permit(:course_id, :catalog_number, :course_name, :term, :campus, :credit_hour, :academic_career, :course_discription)
    end

end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_course.html.erb
<div id="<%= dom_id course %>">
</div>

app/views/courses/_form.html.erb
<%= form_with(model: course) do |form| %>
  <% if course.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
        <% course.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/courses/edit.html.erb
  <%= form_with(model: [@course], local: true) do |form| %>
  
  <div class="form-box">
    <h3 style="margin-bottom:20px;">Editing for CSE <%= @course.catalog_number %></h3>
    <div class="field">
      <%= form.label :course_id, "Course ID" %><br>
      <%= form.number_field :course_id, required: true %>
    </div>

    <div class="field">
      <%= form.label :catalog_number %><br>
      <%= form.text_field :catalog_number, required: true %>
    </div>

    <div class="field">
      <%= form.label :course_name, "Course Title" %><br>
      <%= form.text_area :course_name, required: true, rows: 3, cols: 60 %>
    </div>

    <div class="field">
      <%= form.label :term %><br>
      <%= form.text_field :term, required: true %>
    </div>

    <div class="field">
      <%= form.label :campus %><br>
      <%= form.text_field :campus, required: true %>
    </div>

    <div class="field">
      <%= form.label :credit_hour %><br>
      <%= form.number_field :credit_hour%>
    </div>


    <div class="field">
      <%= form.label :academic_career %><br>
      <%= form.text_field :academic_career, required: true %>
    </div>

    <div class="field">
      <%= form.label :course_discription %><br>
      <%= form.text_area :course_discription, required: true, rows: 6, cols: 120 %>
    </div>

    <div class="actions" style="float:left;">
      <%= form.submit "Save Course" %>
    </div>

    <% end %>

    <br><br>
    
    <div>
      <%= link_to "Back to courses", courses_path %>
    </div>

app/views/courses/index.html.erb
<header class="top-bar">
  <!-- Left side -->
  <div class="top-bar-left">
    <div class="name-box">
      <span>Welcome, <%= @person.first_name + " " + @person.last_name%></span>
    </div>
  </div>
  <div class="logo">
      <%= image_tag 'osu.png', alt: 'OSU image'%>
  </div>
  <!-- Right side -->
  <div class="top-bar-right">
    <!-- notice -->
    <%= notice %>
    <%= link_to "Change my info", edit_user_registration_path, class: 'action-button' %>
    <%= link_to 'Logout', destroy_user_session_path, class: 'action-button' %>
    <% if @person.role == 'admin'%>
      <%= link_to "Manage Request", role_requests_path, class: 'action-button' %>
      <%= form_tag(reset_courses_path, method: :post) do %>
      <%= hidden_field_tag :reset, true %>
      <!-- Reset button -->
      <%= submit_tag "Reset", class: "action-button"%>
    <% end %>
    <% end %>
  </div>
</header>


<!-- Search function for correct courses -->
<div class="search-inputs">
  <%= form_tag(courses_path, method: :get) do %>
    <%= text_field_tag :search_query, params[:search_query], placeholder: "Search Course Catalog Number", name: 'search_query' %>
    <%= select_tag :academic_career, 
          options_for_select([['All Academic Career', nil]] + @academic_careers.map { |career| [career, career] }, params[:academic_career]), 
          include_blank: false, name: 'academic_career' %>
    <%= select_tag :campus, 
          options_for_select([['All Campus', nil]] + @campus.map { |career| [career, career] }, params[:campus]), include_blank: false, name: 'campus' %>
    <%= select_tag :term,
          options_for_select([['All Term', nil]] + @term.map { |career| [career, career] }, params[:term]), include_blank: false, name: 'term' %>
    <%= submit_tag "Search" %>
  <% end %>

</div>

<div id="pagy-nav-top">
  <%== pagy_nav(@pagy) %>
</div>

<div class="courses-box">

  <% @courses.each do |course| %>

  <div class="course">

        <h3>CSE <%= course.catalog_number %></h3> 
        <h4 ><%= course.course_name %></h4> 
        <p><%= course.course_discription %></p> 

        <ul>
              <li id="cr-label">
                <%= course.credit_hour %> units <!-- FIXME: replace these with ruby variables-->
              </li>
              <li id="program-label">
                <%= course.academic_career %>
              </li>
              <li id="campus-label">
                <%= course.campus %>
              </li>
              <li class="right" style="display:flex;">
                <% if @person.role == 'admin'%>
                  <!-- buttons for add section, add course, edit course, delete course -->
                  <%= link_to 'Add course', new_course_path(course), class: 'action-button' %>
                  <%= button_to 'Delete Course', course_path(course), method: :delete, data: { confirm: 'Are you sure?' }, class: 'action-button' %>
                  <%= link_to 'Edit course', edit_course_path(course), class: 'action-button' %>
                  <%= link_to 'Add section', new_course_section_path(course), class: 'action-button' %>
                <% end %>
              </li>
        </ul>
  </div>

    <!-- Run the section and only print the selected sections -->
    <% Section.all.each do |section| %>
      <% if (section.course_id == course.course_id && section.semester_code==course.term && section.campus==course.campus) ||  section.course_id == course.c_id %>
        <div class="section">
          <table>
              <tr>
                <td><h4> Section <%= section.section_id %> (<%= section.s_id%>)</h4></td>
                <td><%unless section.faculty_email.to_s.empty?%>
                    <%person = Person.find(section.faculty_email.to_s)%>
                    <%=person.first_name%> <%=person.last_name%>
                    <% end %></td>
                <td><%= section.weekday.to_s.titleize.delete(",")%></td>
                <td>Grader: <%= section.has_grader%></td>
                <td> <% if @person.role == 'admin'%>
                    <%= link_to 'Edit Section', edit_course_section_path(course, section), class:'section-button'%>
                    <% end %></td>
              </tr>
              <tr>
                <td><h5><%= section.semester_code %></h5></td>
                <td><%= section.faculty_email%></td>
                <td><%unless section.start_time.to_s.empty?%>
                    <%= section.start_time%> - <%= section.end_time%>
                    <%end %></td>
                <td></td>
                <td>
                  <% if @person.role == 'admin'%>
                    <!-- button for delete section -->
                    <%= button_to 'Delete Section', course_section_path(course, section), method: :delete, data: { confirm: 'Are you sure?' }, class:'section-button'%>
                  <% end %>
                </td>
              </tr>
          </table>
        </div>
      <% end %>
    <% end %>
  <% end %>
</div>

<div id="pagy-nav-bottom">
  <%== pagy_nav(@pagy) %>
</div>

app/views/courses/new.html.erb
  <%= form_with(model: [@course], local: true) do |form| %>

  <div class="form-box">
    <h3 style="margin-bottom:20px;">Add Section for CSE <%= @course.catalog_number %></h3>
    <div class="field">
      <%= form.label :course_id, "Course ID" %><br>
      <%= form.number_field :course_id, required: true %>
    </div>

    <div class="field">
      <%= form.label :catalog_number %><br>
      <%= form.text_field :catalog_number, required: true %>
    </div>

    <div class="field">
      <%= form.label :course_name, "Course Title" %><br>
      <%= form.text_area :course_name, required: true, rows: 3, cols: 60 %>
    </div>

    <div class="field">
      <%= form.label :term %><br>
      <%= form.text_field :term, required: true %>
    </div>

    <div class="field">
      <%= form.label :campus %><br>
      <%= form.text_field :campus, required: true %>
    </div>

    <div class="field">
      <%= form.label :credit_hour %><br>
      <%= form.number_field :credit_hour%>
    </div>


    <div class="field">
      <%= form.label :academic_career %><br>
      <%= form.text_field :academic_career, required: true %>
    </div>

    <div class="field">
      <%= form.label :course_discription %><br>
      <%= form.text_area :course_discription, required: true, rows: 6, cols: 120 %>
    </div>

    <div class="actions" style="float:left;">
      <%= form.submit "Add Course" %>
    </div>

    <% end %>

    <br><br>
    
    <div>
      <%= link_to "Back to courses", courses_path %>
    </div>

app/views/courses/reload.html.erb
<h1> Reload Course and Section</h1>

<p>Are you sure you want reload course and section data? This action will take a while</p>

<%= form_with url: perform_reload_courses_path, method: 'post' do %>
  <div class="actions">
    <%= submit_tag 'Confirm' %>
    <%= button_to 'Go back', courses_index_path, method: :get, form_class: 'button_to-inline' %>
  </div>
<% end %>

<style>
  .button_to-inline {
    display: inline;
  }
</style>

app/views/courses/show.html.erb
<%
=begin%>
 Show if operation is successful 
<%
=end%>
<p style="color: green"><%= notice %></p>

<%= render @course %>

<div>
  <%= link_to "Edit this course", edit_course_path(@course) %> |
  <%= link_to "Back to courses", courses_path %>

  <%= button_to "Destroy this course", @course, method: :delete %>
</div>