config/routes.rb
Rails.application.routes.draw do
  resources :sections
  #resources :courses

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    unlocks: 'users/unlocks'
  }

  authenticated :user do
    root 'courses#index', as: :authenticated_root
  end

  devise_scope :user do
    unauthenticated :user do
      root to: 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  # authenticated :user do
  #   root 'placeholder#welcome', as: :authenticated_root
  # end

  devise_scope :user do
    root to: "devise/sessions#new"
  end

  # lab3 part
  # get 'student_information', to: 'students#information', as: 'student_information'

  # lab3 part
  # resources :students do
  #   collection do
  #     # post 'setgpa' 
  #     post 'settime'
  #  end
  # end 


  # # Defines the root path route ("/")
  # root "courses#index"


  resources :courses, only: [:index]
  
   # Reset database route
  post '/reset_courses', to: 'courses#reset'

  # Edit course route
  get 'courses/edit', to: 'courses#edit'

  # New course route
  get 'courses/new', to: 'courses#new'

  #Redirect show page to course index
  get 'courses/:id', to: 'courses#index'

  get 'courses/:id/sections/:id', to: 'courses#index'

  # courses/course_id/section/:id route
  resources :courses do
    resources :sections
  end


  # config/routes.rb
  resources :role_requests do
    member do
      put 'approve'
      put 'deny'
    end
  end

end

app/models/role_request.rb
class RoleRequest < ApplicationRecord
    class RoleRequest < ApplicationRecord
        validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }  #must have email
        validates :role_requested, presence: true, inclusion: { in: %w(student admin instructor) }
        validates :status, inclusion: { in: %w(pending done) }   #status only have 2
      end    
end

app/controllers/role_requests_controller.rb
class RoleRequestsController < ApplicationController
    #before_action :set_role_request
    # def new
    #   @role_requests = RoleRequest.all 
    # end
    def index
      @role_requests = RoleRequest.all  
    end

    # approve for a user account to be a instructor or a admin
    def approve
      @role_request = RoleRequest.find(params[:id]) # Fetch the specific role request by ID
      @person = Person.find(@role_request.email)
      if @role_request.status == 'pending'
        if @role_request.update(status: 'approved')
          @person.update(role: @role_request.role_requested)
          redirect_to role_requests_url, notice: 'Role request was successfully approved.'
        else
          redirect_to role_requests_url, alert: 'Error occurred while approving the role request.'
        end
      else
        redirect_to role_requests_url, alert: 'This role request has already been processed.'
      end
    end
    
    # deny for a user account to be a instructor or a admin
    def deny
      @role_request = RoleRequest.find(params[:id]) # Fetch the specific role request by ID

      if @role_request.status == 'pending'
        if @role_request.update(status: 'denied')
          # If the role request status is 'pending', update it to 'denied'
          redirect_to role_requests_url, notice: 'Role request was successfully denied.'
        else
          redirect_to role_requests_url, alert: 'Error occurred while denying the role request.'
        end
      else
        redirect_to role_requests_url, alert: 'This role request has already been processed.'
      end
    end  
    

    
      private
    
      # Use callbacks to share common setup or constraints between actions.
      def set_role_request
        @role_request = RoleRequest.find(params[:id])
      end
    
      # Only allow a list of trusted parameters through.
      def role_request_params
        params.require(:role_request).permit(:email, :role_requested, :status)
      end
  end
  

app/helpers/role_requests_helper.rb
module RoleRequestsHelper
end

app/views/role_requests/index.html.erb
<h1>Approve Requests</h1>
<%
=begin%>
This is the page for approve and deny requests 
<%
=end%>
<div class="card">
  <div class="requestListContainer">
    <table>
      <tr>
        <th>Email</th>
        <th>Role Requested</th>
        <th>Status</th>
      </tr>

      <% @role_requests.each do |request| %>
        <tr>
          <td style="padding-right: 20px;"><%= request.email %></td>
          <td style="padding-right: 20px;"><%= request.role_requested %></td>
          <td style="padding-right: 20px;"><%= request.status %></td>
          <td>
            <% if request.status == 'pending' %>
                <%= button_to 'Approve', approve_role_request_path(request), method: :put, class: 'btn-approve' %>
                <%= button_to 'Deny', deny_role_request_path(request), method: :put, class: 'btn-deny' %>
            <% else %>
                <!--
                <span>Status: <%= request.status.capitalize %></span>
                -->
            <% end %>
          </td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

<div>
  <%= link_to "Back to courses", courses_path, class: 'back-button' %>
</div>